// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxkpZA1LhF-Xb38B9TODZCiMq7LpoNuXU',
    appId: '1:638320411290:web:e05358c400b56438ef9523',
    messagingSenderId: '638320411290',
    projectId: 'salat-janaza-90f4f',
    authDomain: 'salat-janaza-90f4f.firebaseapp.com',
    storageBucket: 'salat-janaza-90f4f.appspot.com',
    measurementId: 'G-M3Z3R17TTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpRxU8zLRcX2C6MFOhEJVOl10N3dlUuzw',
    appId: '1:638320411290:android:7f22c40dec199ec6ef9523',
    messagingSenderId: '638320411290',
    projectId: 'salat-janaza-90f4f',
    storageBucket: 'salat-janaza-90f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ8sNfBZ0t1zxCZGCyHWkncPscAE_2HBY',
    appId: '1:638320411290:ios:d6c435636c9d4f40ef9523',
    messagingSenderId: '638320411290',
    projectId: 'salat-janaza-90f4f',
    storageBucket: 'salat-janaza-90f4f.appspot.com',
    iosClientId: '638320411290-cnuvago8gbkt7jakaf4c3nvb02dbbuei.apps.googleusercontent.com',
    iosBundleId: 'com.salatjanaza.salatJanaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ8sNfBZ0t1zxCZGCyHWkncPscAE_2HBY',
    appId: '1:638320411290:ios:d6c435636c9d4f40ef9523',
    messagingSenderId: '638320411290',
    projectId: 'salat-janaza-90f4f',
    storageBucket: 'salat-janaza-90f4f.appspot.com',
    iosClientId: '638320411290-cnuvago8gbkt7jakaf4c3nvb02dbbuei.apps.googleusercontent.com',
    iosBundleId: 'com.salatjanaza.salatJanaza',
  );
}
